### PR TITLE
minor updates for CRAN resubmisson

### PR DESCRIPTION
**Pull request by dm807cam**
- bump version from 0.3.0 to 0.3.1
- adjust package call in zzz
- initiate `seawater_correction`

### CODE REVIEW

**Comment by oscarbranson** [comment]
Should this be 0.3.2, as python has already taken 0.3.1? Or are we ok with non-unique '.Z' numbers?

**Comment by oscarbranson** [comment]
Aaalso, can you please update HISTORY.md?

**Comment by dm807cam** [comment]
> Should this be 0.3.2, as python has already taken 0.3.1? Or are we ok with non-unique '.Z' numbers?

Since CRAN version is 3.1 now I believe we should keep it 3.1 here as well. I also believe to remember that we said that .Z numbers are detached from global versioning and just used as language internal indicators, didn't we?

**Comment by oscarbranson** [comment]
We did, although I must admit in my head I'd presumed we'd still have unique version numbers (i.e. there would only be on 0.3.1 version, but it would only exist in Python)... but I guess not! Not a big deal, as long as it's all documented in `HISTORY.md`!

**Pull request merged**
